-- mysql
SELECT I.ANIMAL_ID, I.NAME 
FROM ANIMAL_INS AS I
RIGHT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;

-- oracle
SELECT *
FROM (
    SELECT I.ANIMAL_ID, I.NAME FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY TO_DATE(O.DATETIME)-TO_DATE(I.DATETIME) DESC
) 
WHERE ROWNUM < 3
